fabric8-ui/fabric8-recommender

src/app/analyze/stack/recommender/recommender.component.ts
src/app/analyze/stack/recommender/recommender.html
src/app/analyze/stack/recommender/recommender.module.ts
src/app/analyze/stack/recommender/recommender.scss
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.spec.ts
src/app/analyze/stack/stack-details/stack-details.component.ts
src/app/analyze/stack/stack-details/stack-details.module.ts
src/app/analyze/stack/stack-overview/stack-overview.component.html

1. Initial setup of Scss, html, module, component
2. Static HTML that displays the structure of the recommendation section as per mock
3. Styles for supporting the html
4. In components, added an input to dynamically get data from the parent component
5. In module, included the component and other necessary dependencies.
In Stack-details section
1. Changes in the stack-details.component.html that includes the new recommender module.
2. Change in stack-details.component.ts that provides the input to the new component
Change in stack-overflow.component.html to check if the space is present as it throws error on reload from the Stack route.
Changes in the test case to include this new module (Includes the recommender module import).
Tracks #6.

Includes the recommender module - as per mock

---

src/app/analyze/stack/stack-details/stack-details.component.html

fixes #4 , created and modal and moved stack report content on it, formatted HTML code.

created and modal and moved stack report content on it

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.html
src/app/analyze/stack/stack-components/stack-components.module.ts
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.spec.ts
src/app/analyze/stack/stack-details/stack-details.module.ts

The changes are
1. Inclusion of Module, Component, HTML, SCSS
2. Changes in the test case to include this module
Added the selector in the stack-details.html for this to show up in the UI.
Added the newly created module in the stack-details.module.ts for the application to know.
This is just the initial commit that has the structure.
Tracks #6.

Created a basic structure for the stack-components section.

---

src/app/analyze/stack/pager.service.ts
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.ts

- Have moved recommender grid component on Modal
- Have added a service to handle pagination in client side , currently implemented for recommender grid

Recommender pagination

---

src/app/analyze/stack/recommender/recommender.component.ts
src/app/analyze/stack/recommender/recommender.html
src/app/analyze/stack/recommender/recommender.scss
src/app/analyze/stack/stack-details/stack-details.component.ts

1. Checkboxes,
2. Dropdown Action
Passing the input from the parent component to the recommender component (Child) so it can be easily consumed
Handled events specific to recommendation component
Handled actions in the case of individual items addition, 
Multiple item addition is pending and in progress.
Tracks #6.

Created actions for,

---

src/app/analyze/stack/recommender/recommender.component.ts
src/app/analyze/stack/stack-details/stack-details.component.ts

-made changes as per sample response for Stack analyses
-implemented onChanges in recommender for pagination binding

changes as per sample response for Stack analyses

---

src/app/analyze/stack/recommender/recommender.component.ts
src/app/analyze/stack/recommender/recommender.html
src/app/analyze/stack/recommender/recommender.scss
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.ts

1. Changes in the recommender.component.ts file to handle the multiple selection and deselection events.
a. Takes care if manually selecting all checkboxes - Automatically checks the Select all checkbox
b. Same goes for Deselection
c. Highlighting and dehiglighting in case of multiple selection
2. Changes in the recommender.html to support the same
Commented out the functionality of the pagination for now as it is not in the mock. The same will be brought back in case required.
Tracks #6.

Functionality for the multiple checkbox selection.

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.html
src/app/analyze/stack/stack-components/stack-components.module.ts
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.ts

created template for dependency grid with patternfly, added to modal.

created template for dependency grid with patternfly, added to modal

---

src/app/analyze/stack/stack-details/stack-details.component.html

Remove markup that is no longer needed.

Remove unused template code

---

src/app/analyze/stack/recommender/recommender.component.ts
src/app/analyze/stack/recommender/recommender.html

Changes in this commit:
1. Handles the case for restoring already dismissed work item
2. Disables create work item link when the work item is disabled
3. Enables Restore link only when the item is dismissed
4. Handles links for multiple scenario.
Tracks #16.

Implemented Restore Recommendation Feature

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.html
src/app/analyze/stack/stack-components/stack-components.module.ts
src/app/analyze/stack/stack-components/table-filter.pipe.ts

1. Added a new Pipe for handling dynamic filter.
2. Changes in the html to fit the filter
3. Changes in the component to use the filter
4. Changes in the module to add the filter and export it to be able to be used by all components in this module
Tracks #19.

Introduced dynamic filter for the Angular2 table.

---

package.json
src/app/analyze/stack/stack-details/stack-details.component.spec.ts
src/app/analyze/stack/stack-details/stack-details.module.ts

removed dependency of angular2-datatable from package.json, stack module and test files as redundant now

removed dependency of angular2-datatable from package and test files

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.html
src/app/analyze/stack/stack-components/table-filter.pipe.ts
src/app/analyze/stack/stack-details/stack-details.component.ts

What this commit has?
1. Changes in the pipe - Removed the case checking as it was not helping
2. Changes in the html - To accomodate the dropdown changes and removed unnecessary code
3. Changes in the component - To handle events fired on change of dropdown, button click
4. Changes in the json to make it usable
5. Corrected some lint issues
Tracks #19

Changes in the table to make it respond to the dynamic filter.

---

package.json
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.scss
src/app/analyze/stack/stack-details/stack-details.component.ts
src/app/shared/dummy.service.ts

-Handled response,failure scenario for stack-analyses API
-Made changes to modal as per UX in case of no response/failure
-Styling of modal
-Added static progress bar to modal
-Changed ngx-fabric8-wit version to 0.1.0 from 0.0.0 as it's was breaking.

-Handled response,failure scenario for stack-anlyses API/ Modal styling

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.html
src/app/analyze/stack/stack-components/stack-components.module.ts
src/app/analyze/stack/stack-components/stack-components.scss
src/app/analyze/stack/stack-components/table-orderby.pipe.ts
src/app/analyze/stack/stack-details/stack-details.component.spec.ts

Changes in this commit:
1. Stack Components Table gets the dynamic sorting functionality.
2. Removed the hardcode for table headers from html and moved It to component level
3. Added a key set that loops through and sets the keys for the object. This can be generic and hence the changes are required in only one place if any comes up.
4. Created a new generic dynamic Pipe for getting this sorting functionality.
5. Added the dependencies in the Module.
6. Updated the test case for enabling this Overview module.
Tracks #19

Table sorting functionality.

---

src/app/analyze/stack/overview/overview.component.ts
src/app/analyze/stack/overview/overview.html
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.scss
src/app/analyze/stack/stack-details/stack-details.component.ts

-Stack Overview static charts and CVEs as per mockup

Stack Overview static charts and CVEs as per mockup

---

src/app/analyze/stack/stack-components/stack-components.html
src/app/analyze/stack/stack-components/stack-components.scss

1. Added a class in the html
2. Added a few styles for the same class to make the feature to be in sync with the mock.
Tracks #19.

Style changes for Stack components feature

---

src/app/analyze/stack/stack-analyses.service.ts
src/app/analyze/stack/stack-details/stack-details.component.ts

1. Changed the code to fit to the API format change.
2. Removed unused code snippets
3. Made variables for holding frequently used json
Fixes #30.

Fixes #30. Refactor for the API change.

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.ts

1. Removed the hardcoded values that were shown in the table
2. Added the API response for those that were available
3. For those that don’t have the response, NA will be shown
4. Changes made in the component to support the above statements
Tracks #19

Stack Dependencies - Integration of API response

---

src/app/analyze/stack/overview/overview.component.spec.ts
src/app/analyze/stack/recommender/recommender.component.spec.ts
src/app/analyze/stack/stack-components/stck-components.component.spec.ts

added test spec for Overview, Recommender , Stack Components with initial test

added test spec for Overview, Recommender , Stack Components

---

src/app/analyze/stack/stack-details/stack-details.component.ts

Changes in this commit.
1. Changes in the stack-details.component.ts to handle the worst case scenario.
2. Removed getRecommendations() function and handled it to suit the response.
a. If the response doesn't have any required things, an error message will be shown,
b. If the response has results but no recommendations, then results will be shown,
c. If the response has recommendations but no results, then only recommendations will be shown.

Fixes #36. Handled the API response in case of failure scenario.

---

src/app/analyze/stack/overview/overview.component.spec.ts
src/app/analyze/stack/overview/overview.component.ts

-Overview component unit test cases
-Code refactoring of overview component

Overview component test cases

---

src/app/analyze/stack/recommender/recommender.component.spec.ts
src/app/analyze/stack/recommender/recommender.html

1. Tests for the validity of the component
2. Checks if the function createWorkItems works fine
3. Checks if the toggleWorkItem function works fine
4. Checks if the handleRestoreWorkItemAction function works fine
5. Checks if the recommendations have properly got toggled for dismissWorkItemCase
6. Checks if the recommendations have properly got toggled for restoreWorkItemCase
1. Tests for changes in the HTML DOM onrendering of the input value.
2. Ensures the function gets called on the respective button click.
3. Checks if the className is properly received on various input levels
a. Should receive 'activate' on a few cases
b. Should receive 'deactivate' on a few cases.
1. Checks the functionality of the Addworkflow service by mocking it.
2. Checks if canCreateWorkItem() function can be …

Test case for RecommenderComponent

---

src/app/analyze/stack/stack-components/table-filter.pipe.spec.ts
src/app/analyze/stack/stack-components/table-orderby.pipe.spec.ts

-Added Unit tests filters used for sort in stack components
-Added Unit tests filters used for OrderBy in stack components

Unit test filters/pipes in stack components

---

src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.scss
src/app/analyze/stack/stack-overview/stack-overview.component.ts
src/app/analyze/stack/stack-overview/stack-overview.module.ts
src/app/analyze/stack/stack-routing.module.ts
src/app/analyze/stack/stack.component.ts
src/app/analyze/stack/stack.module.ts

-Have removed unused Imports
-Have removed unwanted code blocks

cleaned unused imports, code

---

src/app/analyze/stack/stack-details/stack-details.component.html
src/app/analyze/stack/stack-details/stack-details.component.spec.ts

1. A class in html for accessing that in the test case
2. Test Case for checking on click of a button, the modal should open
3. Test case for checking if the getAnalyses function on load of ngOnInit

Test cases for Stack Details Component

---

src/app/analyze/stack/recommender/recommender.component.ts
src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-details/stack-details.component.ts

1. Added meaningful comments
2. Removed repetitive code and made it proper
3. Added proper type checks
4. Basic refactoring

Refactor of StackDetailsComponent

---

src/app/analyze/stack/constants/constants-mapper.ts
src/app/analyze/stack/constants/constants.service.ts
src/app/analyze/stack/constants/constants.stack-details.ts
src/app/analyze/stack/constants/constants.stack-recommender.ts
src/app/analyze/stack/constants/global-constants.ts
src/app/analyze/stack/stack-details/stack-details.component.ts
src/app/analyze/stack/stack-details/stack-details.module.ts

What it does?
Introduces a new Global Constant implementation that enables to replace direct hardcoded strings in HTML, TS to be fetched from Constants.
How does it affect?
It enables easier access of constants for reading, editing and deleting.
Things will be done in one place and hence can be reused across.
Changes in this commit:
1. A generic service constants.service.ts that handles the rendering of messages of the desired component
2. A constants-mapper.ts that maps the constants file of a component against a name that can be used for retrieving.
3. n constant files each representing a component.
4. A global-constants.ts file that includes all the constants files.
Tracks #33.

Global Constants - Implemenation ( Structure ready )

---

src/app/analyze/stack/overview/overview.html
src/app/analyze/stack/stack-components/stack-components.component.ts
src/app/analyze/stack/stack-components/stack-components.html

removed component usage, dependent's count graph, component grid (data added , team usage, popularity with value -1 replaced with NA)

removed unneeded ux changes

---

package.json
src/app/app.module.ts
src/app/stack/constants/constants.stack-recommender.ts
src/app/stack/recommender/recommender.component.html
src/app/stack/recommender/recommender.component.scss
src/app/stack/recommender/recommender.component.ts
src/app/stack/recommender/recommender.module.ts
src/app/stack/stack-components/stack-components.component.ts
src/app/stack/stack-details/add-work-flow.service.ts
src/app/stack/stack-details/stack-details.component.ts

1. changes the layout fixing minor ux faults.
2. changes the api url for creation and viewing of created work items
a. Changes in the Payload information - Test only
b. Changes in the version number of the ngx-fabric8-wit in package.json
3. refactors the codebase
4. changes the ui to temporarily [until the ux is finalized] show the response as a link below recommendations after successful creation of workitems
Also,
5. Adds Contexts in the app.module.ts to make it properly work in the demo repository.
6. Adds HTML, CSS changes for showing the link and hiding the link.
changes the version in package.json from 0.0.2 to 0.0.3

Changes with API url structure and a few other things

---

src/app/stack/stack-details/add-work-flow.service.ts

Fixes https://github.com/fabric8io/fabric8-ui/issues/393 on platform - space can be null when going back home

fix(nullref): make sure space is available when context changes

---

config/webpack.dev.js
src/app/stack/stack-analyses.service.ts

1. Handles the standalone case
2. Handles the dynamic case.
Fixes: #76

fix(url): change the url from hardcode to render dynamically.

---

src/app/stack/constants/constants.overview.ts
src/app/stack/overview/overview.component.html
src/app/stack/overview/overview.component.scss
src/app/stack/overview/overview.component.ts
src/app/stack/recommender/recommender.component.html
src/app/stack/recommender/recommender.component.scss
src/app/stack/stack-analyses.service.ts
src/app/stack/stack-components/stack-components.component.scss
src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.scss
src/app/stack/stack-details/stack-details.component.ts

Overview section updates for the dependencies and metrics section. Using the api data now

feat(stack overview): add new overview feature changes

---

src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts

Call stack analysis service only after click of button

---

src/app/app.component.ts
src/app/stack/constants/constants.overview.ts
src/app/stack/overview/overview.component.html
src/app/stack/overview/overview.component.scss
src/app/stack/overview/overview.component.ts
src/app/stack/stack-analyses.service.ts
src/app/stack/stack-components/stack-components.component.html
src/app/stack/stack-components/stack-components.component.scss
src/app/stack/stack-components/stack-components.component.ts
src/app/stack/stack-details/stack-details.component.ts

1. Added the security tile card in overview section
2. Added the license card with the chart in overview section
3. Added the new columns to the components grid.
4. Style fixes

Stack overview security

---

index.ts
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/utils/stack-api-utils.ts

Changes:
1. Stack details component file refactors to reuse the utils
2. Introduces utils to reuse the functionalities of stack analysis.
3. Introduces new exports in index.ts

fix(exportable): change in code structure to make it exportable and reusable

---

src/app/shared/toast-notification/toast-notification.component.html
src/app/shared/toast-notification/toast-notification.component.scss
src/app/shared/toast-notification/toast-notification.component.ts
src/app/stack/constants/constants.stack-recommender.ts
src/app/stack/overview/overview.component.html
src/app/stack/overview/overview.component.scss
src/app/stack/overview/overview.component.ts
src/app/stack/recommender/recommender.component.html
src/app/stack/recommender/recommender.component.ts
src/app/stack/recommender/recommender.module.ts
src/app/stack/stack-details/stack-details.component.scss
src/app/stack/stack-details/stack-details.component.ts

Changes:
1. Component, HTML, Scss added for toast implementation

fix(toast): add the toast notification for work item response

---

src/app/stack/constants/constants.stack-recommender.ts
src/app/stack/recommender/recommender.component.html
src/app/stack/recommender/recommender.component.scss
src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts

fix the distortion in recommender view in runtimeconsole space and exposed a way to dynamically add text for the Stack Reports link

fix(bug): fix the distortion in recommender view in runtimeconsole space and exposed a way to dynamically add text for the Stack Reports link

---

src/app/stack/stack-components/stack-components.component.ts

Changes for fixing 'NA' issue

---

src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts

Handle modal close to clear the persisted view state.

---

src/app/stack/constants/constants.overview.ts
src/app/stack/overview/chart-component.ts
src/app/stack/overview/overview.component.html
src/app/stack/overview/overview.component.scss
src/app/stack/overview/overview.component.ts

- Added the responsive classes to the overview cards
- License chart improvement
* Show number of licenses.
* Limit the legends in the chart to 4 and show the remaining as 'Others'

Alignment fixes and Improvements to license chart

---

README.adoc
config/webpack.dev.js
src/app/app.module.ts
src/app/shared/mock-auth.service.ts

…he API results without having to manually pass on a token everytime.
Fixes #222.

Enables the standalone recommender to function properly in fetching the API results without having to manually pass on a token every time.

---

cico_run_tests.sh

Adapt script to run ci centos tests

---

src/app/app.component.ts
src/app/stack/overview/overview.component.ts
src/app/stack/stack-components/stack-components.component.html
src/app/stack/stack-components/stack-components.component.scss
src/app/stack/stack-components/stack-components.component.ts
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/utils/stack-api-utils.ts

Changes the Stack API utils file to expose more data so it can be consumed from across. 
Corrects the typo from potentially to potential
Corrects the bug for dependencies' code metrics count -1, -2 to NA
Corrects the text overflow problem in the dependencies table.
Fixes #244 #257 #249

fix(bug): typo, dependencies -1 bug, api changes, text-overflow problem

---

src/app/stack/stack-details/stack-details.component.ts

fix(bug): typo fix

---

src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts

Fixes: https://github.com/openshiftio/openshift.io/issues/583

fix(bug): change in the input structure to accept more inputs to display app name and build number

---

src/app/stack/stack-details/stack-details.component.ts

Tracks: https://github.com/openshiftio/openshift.io/issues/584

fix(issue): fix the bug that causes problems during no recommendations flow.

---

README.adoc
src/app/stack/component-level/component-level.component.ts

fix(work_item_creation):fixed issue with viewing created work item in planner from stack report
https://github.com/openshiftio/openshift.io/issues/746

fix(work_item_creation):fixed issue with viewing created work item

---

src/app/stack/component-level/component-level.component.ts
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/stack-level/stack-level.component.ts
src/app/stack/stack-report-inshort/stack-report-inshort.component.ts

Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>

fix(deps-structure): fixed dependency structure issue

---

src/app/stack/component-level/component-level.component.ts
src/app/stack/stack-analyses.service.ts
src/app/stack/stack-details/stack-details.component.html
src/app/stack/stack-details/stack-details.component.ts
src/app/stack/stack-level/stack-level.component.html
src/app/stack/stack-level/stack-level.component.less
src/app/stack/stack-level/stack-level.component.ts
src/app/stack/stack-report-inshort/stack-report-inshort.component.html
src/app/stack/stack-report-inshort/stack-report-inshort.component.less
src/app/stack/stack-report-inshort/stack-report-inshort.component.ts

https://github.com/openshiftio/openshift.io/issues/1428

Licences fix

---

README.adoc
src/app/stack/stack-details/stack-details.component.less

fix for https://github.com/openshiftio/openshift.io/issues/816

fix(bug): fixed issue with scroll on page

---

src/app/stack/report-summary/report-summary-card/report-summary-card.component.html
src/app/stack/report-summary/report-summary-card/report-summary-card.component.ts
src/app/stack/report-summary/report-summary-card/report-summary-content/report-summary-content.component.html
src/app/stack/report-summary/report-summary-card/report-summary-content/report-summary-content.component.less
src/app/stack/report-summary/report-summary-card/report-summary-content/report-summary-content.component.ts
src/app/stack/stack-report-inshort/stack-report-inshort.component.html
src/app/stack/utils/common.service.ts

1. Added message if no security found
2. Updated eventemitter to subject for events subscription

fix(bug-fix): Added no security message and dashboard card click

---

src/app/stack/card-details/component-information/component-information.component.html

Tracks: https://github.com/openshiftio/openshift.io/issues/2963

fix(bug): fix work item creation for empty state.

---

src/app/stack/utils/component-feedback/component-feedback.component.html
src/app/stack/utils/component-feedback/component-feedback.component.less
src/app/stack/utils/component-feedback/component-feedback.component.ts

Tracks https://github.com/openshiftio/openshift.io/issues/3194

fix(bug): notification has been removed from feedback and it is made more intuitive.

---

src/app/stack/pipeline-insights/pipeline-insights.component.ts
src/app/stack/stack-details/stack-details.component.html

Removes console log from pipeline insights component
Enables caching of the response if any.

fix(console): removes console log and caches the response from the previous calls if any

---

cico_build_deploy.sh
cico_release.sh
cico_run_tests.sh
cico_setup.sh
package-lock.json
package.json

This PR is to move away from the GKE build framework to centos-ci.
Addresses :- https://github.com/openshiftio/openshift.io/issues/3745

feat(cicd): move away from GKE to Centos build

---

README.adoc

fix(build): trigger the commit build

---

cico_release.sh

- Fix the commit build for now.
- Once I fix this https://ci.centos.org/view/Devtools/job/devtools-fabric8-recommender-npm-publish-build-master/3/console I will again uncomment the line
Addresses :- https://github.com/openshiftio/openshift.io/issues/3745

fix(build): fix the commit build

---

src/app/stack/card-details/card-details.component.spec.ts
src/app/stack/card-details/component-details/component-details.component.spec.ts
src/app/stack/card-details/component-information/component-information.component.spec.ts
src/app/stack/card-details/report-information/no-data/no-data.component.spec.ts
src/app/stack/card-details/report-information/report-information.component.spec.ts
src/app/stack/feedback/feedback.service.ts
src/app/stack/pipeline-insights/pipeline-insights.component.ts
src/app/stack/pipeline-insights/pipeline-insights.module.ts
src/app/stack/pipeline-insights/pipeline-insights.service.ts
src/app/stack/report-summary/report-summary-card/report-summary-card.component.spec.ts
src/app/stack/report-summary/report-summary-card/report-summary-content/report-info-entries/report-info-entries.component.spec.ts
src/app/stack/report-summary/report-summary-card/report-summary-content/report-summary-content.component.spec.ts
src/app/stack/report-summary/report-summary-card/report-summary-title/report-summary-title.component.spec.ts
src/app/stack/report-summary/report-summary.component.spec.ts
src/app/stack/stack-analyses.service.ts
src/app/stack/stack-details/add-work-flow.service.ts
src/app/stack/stack-details/stack-details-component.spec.ts
src/app/stack/stack-details/stack-details.module.ts
src/app/stack/stack-report-inshort/stack-report-inshort.component.ts
src/app/stack/utils/component-feedback/component-feedback.component.spec.ts
src/app/stack/utils/component-feedback/component-feedback.service.ts

Refactored repo to use HttpClient.

fix(httpclient): move to HttpClient in preparation for ng6

---

README.adoc
package-lock.json
projects/fabric8-stack-analysis-ui/src/lib/stack/card-details/report-information/report-information.module.ts
projects/fabric8-stack-analysis-ui/src/lib/stack/utils/component-feedback/component-feedback.service.ts

- Fixes issue with the header not being set for component feedback API
- Removes unneeded imports
Tracks : https://github.com/openshiftio/openshift.io/issues/4363

Fix component feedback
